name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        java: [17, 11]

    name: Build with Java ${{ matrix.java }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Build with Maven
      run: mvn -f pom.xml clean verify
