name: Java CI with Maven

on:
	push:
	pull request:

jobs:
	build:
		runs-on: macos-latest
			
	steps:
	- uses: actions/checkout@v2
	- name: Set up JDK 17
	
	uses: actions/setup-java@v1
	with:
		java-version: 1.8
	- name: Build with Maven
	  run: mvn -f com.examples.myproject/pom.xml clean verify